// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package producer

import (
	"context"
	"github.com/not-for-prod/broker"
	"sync"
)

// Ensure, that BrokerMock does implement Broker.
// If this is not the case, regenerate this file with moq.
var _ Broker = &BrokerMock{}

// BrokerMock is a mock implementation of Broker.
//
//	func TestSomethingThatUsesBroker(t *testing.T) {
//
//		// make and configure a mocked Broker
//		mockedBroker := &BrokerMock{
//			PushFunc: func(ctx context.Context, r []broker.Event) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedBroker in code that requires Broker
//		// and then make assertions.
//
//	}
type BrokerMock struct {
	// PushFunc mocks the Push method.
	PushFunc func(ctx context.Context, r []broker.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Push holds details about calls to the Push method.
		Push []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R []broker.Event
		}
	}
	lockPush sync.RWMutex
}

// Push calls PushFunc.
func (mock *BrokerMock) Push(ctx context.Context, r []broker.Event) error {
	if mock.PushFunc == nil {
		panic("BrokerMock.PushFunc: method is nil but Broker.Push was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   []broker.Event
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(ctx, r)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedBroker.PushCalls())
func (mock *BrokerMock) PushCalls() []struct {
	Ctx context.Context
	R   []broker.Event
} {
	var calls []struct {
		Ctx context.Context
		R   []broker.Event
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
