// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package producer

import (
	"context"
	"github.com/not-for-prod/broker"
	"sync"
)

// Ensure, that StorageMock does implement Storage.
// If this is not the case, regenerate this file with moq.
var _ Storage = &StorageMock{}

// StorageMock is a mock implementation of Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked Storage
//		mockedStorage := &StorageMock{
//			CommitOffsetFunc: func(ctx context.Context, producerName string, offset uint64) error {
//				panic("mock out the CommitOffset method")
//			},
//			GetOffsetFunc: func(ctx context.Context, producerName string) (uint64, error) {
//				panic("mock out the GetOffset method")
//			},
//			ListRecordsFunc: func(ctx context.Context, limit uint64, offset uint64) ([]broker.Event, error) {
//				panic("mock out the ListRecords method")
//			},
//			PushFunc: func(ctx context.Context, e []broker.Event) error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedStorage in code that requires Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// CommitOffsetFunc mocks the CommitOffset method.
	CommitOffsetFunc func(ctx context.Context, producerName string, offset uint64) error

	// GetOffsetFunc mocks the GetOffset method.
	GetOffsetFunc func(ctx context.Context, producerName string) (uint64, error)

	// ListRecordsFunc mocks the ListRecords method.
	ListRecordsFunc func(ctx context.Context, limit uint64, offset uint64) ([]broker.Event, error)

	// PushFunc mocks the Push method.
	PushFunc func(ctx context.Context, e []broker.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// CommitOffset holds details about calls to the CommitOffset method.
		CommitOffset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProducerName is the producerName argument value.
			ProducerName string
			// Offset is the offset argument value.
			Offset uint64
		}
		// GetOffset holds details about calls to the GetOffset method.
		GetOffset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProducerName is the producerName argument value.
			ProducerName string
		}
		// ListRecords holds details about calls to the ListRecords method.
		ListRecords []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit uint64
			// Offset is the offset argument value.
			Offset uint64
		}
		// Push holds details about calls to the Push method.
		Push []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// E is the e argument value.
			E []broker.Event
		}
	}
	lockCommitOffset sync.RWMutex
	lockGetOffset    sync.RWMutex
	lockListRecords  sync.RWMutex
	lockPush         sync.RWMutex
}

// CommitOffset calls CommitOffsetFunc.
func (mock *StorageMock) CommitOffset(ctx context.Context, producerName string, offset uint64) error {
	if mock.CommitOffsetFunc == nil {
		panic("StorageMock.CommitOffsetFunc: method is nil but Storage.CommitOffset was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ProducerName string
		Offset       uint64
	}{
		Ctx:          ctx,
		ProducerName: producerName,
		Offset:       offset,
	}
	mock.lockCommitOffset.Lock()
	mock.calls.CommitOffset = append(mock.calls.CommitOffset, callInfo)
	mock.lockCommitOffset.Unlock()
	return mock.CommitOffsetFunc(ctx, producerName, offset)
}

// CommitOffsetCalls gets all the calls that were made to CommitOffset.
// Check the length with:
//
//	len(mockedStorage.CommitOffsetCalls())
func (mock *StorageMock) CommitOffsetCalls() []struct {
	Ctx          context.Context
	ProducerName string
	Offset       uint64
} {
	var calls []struct {
		Ctx          context.Context
		ProducerName string
		Offset       uint64
	}
	mock.lockCommitOffset.RLock()
	calls = mock.calls.CommitOffset
	mock.lockCommitOffset.RUnlock()
	return calls
}

// GetOffset calls GetOffsetFunc.
func (mock *StorageMock) GetOffset(ctx context.Context, producerName string) (uint64, error) {
	if mock.GetOffsetFunc == nil {
		panic("StorageMock.GetOffsetFunc: method is nil but Storage.GetOffset was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ProducerName string
	}{
		Ctx:          ctx,
		ProducerName: producerName,
	}
	mock.lockGetOffset.Lock()
	mock.calls.GetOffset = append(mock.calls.GetOffset, callInfo)
	mock.lockGetOffset.Unlock()
	return mock.GetOffsetFunc(ctx, producerName)
}

// GetOffsetCalls gets all the calls that were made to GetOffset.
// Check the length with:
//
//	len(mockedStorage.GetOffsetCalls())
func (mock *StorageMock) GetOffsetCalls() []struct {
	Ctx          context.Context
	ProducerName string
} {
	var calls []struct {
		Ctx          context.Context
		ProducerName string
	}
	mock.lockGetOffset.RLock()
	calls = mock.calls.GetOffset
	mock.lockGetOffset.RUnlock()
	return calls
}

// ListRecords calls ListRecordsFunc.
func (mock *StorageMock) ListRecords(ctx context.Context, limit uint64, offset uint64) ([]broker.Event, error) {
	if mock.ListRecordsFunc == nil {
		panic("StorageMock.ListRecordsFunc: method is nil but Storage.ListRecords was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  uint64
		Offset uint64
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListRecords.Lock()
	mock.calls.ListRecords = append(mock.calls.ListRecords, callInfo)
	mock.lockListRecords.Unlock()
	return mock.ListRecordsFunc(ctx, limit, offset)
}

// ListRecordsCalls gets all the calls that were made to ListRecords.
// Check the length with:
//
//	len(mockedStorage.ListRecordsCalls())
func (mock *StorageMock) ListRecordsCalls() []struct {
	Ctx    context.Context
	Limit  uint64
	Offset uint64
} {
	var calls []struct {
		Ctx    context.Context
		Limit  uint64
		Offset uint64
	}
	mock.lockListRecords.RLock()
	calls = mock.calls.ListRecords
	mock.lockListRecords.RUnlock()
	return calls
}

// Push calls PushFunc.
func (mock *StorageMock) Push(ctx context.Context, e []broker.Event) error {
	if mock.PushFunc == nil {
		panic("StorageMock.PushFunc: method is nil but Storage.Push was just called")
	}
	callInfo := struct {
		Ctx context.Context
		E   []broker.Event
	}{
		Ctx: ctx,
		E:   e,
	}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc(ctx, e)
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedStorage.PushCalls())
func (mock *StorageMock) PushCalls() []struct {
	Ctx context.Context
	E   []broker.Event
} {
	var calls []struct {
		Ctx context.Context
		E   []broker.Event
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}

// Ensure, that TxManagerMock does implement TxManager.
// If this is not the case, regenerate this file with moq.
var _ TxManager = &TxManagerMock{}

// TxManagerMock is a mock implementation of TxManager.
//
//	func TestSomethingThatUsesTxManager(t *testing.T) {
//
//		// make and configure a mocked TxManager
//		mockedTxManager := &TxManagerMock{
//			DoFunc: func(ctx context.Context, fn func(context.Context) error) error {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedTxManager in code that requires TxManager
//		// and then make assertions.
//
//	}
type TxManagerMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, fn func(context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(context.Context) error
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *TxManagerMock) Do(ctx context.Context, fn func(context.Context) error) error {
	if mock.DoFunc == nil {
		panic("TxManagerMock.DoFunc: method is nil but TxManager.Do was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, fn)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedTxManager.DoCalls())
func (mock *TxManagerMock) DoCalls() []struct {
	Ctx context.Context
	Fn  func(context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(context.Context) error
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
