// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer

import (
	"context"
	"github.com/not-for-prod/broker"
	"sync"
)

// Ensure, that BrokerMock does implement Broker.
// If this is not the case, regenerate this file with moq.
var _ Broker = &BrokerMock{}

// BrokerMock is a mock implementation of Broker.
//
//	func TestSomethingThatUsesBroker(t *testing.T) {
//
//		// make and configure a mocked Broker
//		mockedBroker := &BrokerMock{
//			CommitFunc: func(ctx context.Context, events []broker.Event) error {
//				panic("mock out the Commit method")
//			},
//			PullFunc: func(ctx context.Context, batchSize uint64) ([]broker.Event, error) {
//				panic("mock out the Pull method")
//			},
//		}
//
//		// use mockedBroker in code that requires Broker
//		// and then make assertions.
//
//	}
type BrokerMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func(ctx context.Context, events []broker.Event) error

	// PullFunc mocks the Pull method.
	PullFunc func(ctx context.Context, batchSize uint64) ([]broker.Event, error)

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Events is the events argument value.
			Events []broker.Event
		}
		// Pull holds details about calls to the Pull method.
		Pull []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// BatchSize is the batchSize argument value.
			BatchSize uint64
		}
	}
	lockCommit sync.RWMutex
	lockPull   sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *BrokerMock) Commit(ctx context.Context, events []broker.Event) error {
	if mock.CommitFunc == nil {
		panic("BrokerMock.CommitFunc: method is nil but Broker.Commit was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Events []broker.Event
	}{
		Ctx:    ctx,
		Events: events,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(ctx, events)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedBroker.CommitCalls())
func (mock *BrokerMock) CommitCalls() []struct {
	Ctx    context.Context
	Events []broker.Event
} {
	var calls []struct {
		Ctx    context.Context
		Events []broker.Event
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Pull calls PullFunc.
func (mock *BrokerMock) Pull(ctx context.Context, batchSize uint64) ([]broker.Event, error) {
	if mock.PullFunc == nil {
		panic("BrokerMock.PullFunc: method is nil but Broker.Pull was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		BatchSize uint64
	}{
		Ctx:       ctx,
		BatchSize: batchSize,
	}
	mock.lockPull.Lock()
	mock.calls.Pull = append(mock.calls.Pull, callInfo)
	mock.lockPull.Unlock()
	return mock.PullFunc(ctx, batchSize)
}

// PullCalls gets all the calls that were made to Pull.
// Check the length with:
//
//	len(mockedBroker.PullCalls())
func (mock *BrokerMock) PullCalls() []struct {
	Ctx       context.Context
	BatchSize uint64
} {
	var calls []struct {
		Ctx       context.Context
		BatchSize uint64
	}
	mock.lockPull.RLock()
	calls = mock.calls.Pull
	mock.lockPull.RUnlock()
	return calls
}
