// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer

import (
	"context"
	"github.com/not-for-prod/broker"
	"sync"
)

// Ensure, that StorageMock does implement Storage.
// If this is not the case, regenerate this file with moq.
var _ Storage = &StorageMock{}

// StorageMock is a mock implementation of Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked Storage
//		mockedStorage := &StorageMock{
//			SetNXFunc: func(ctx context.Context, e []broker.Event) ([]bool, error) {
//				panic("mock out the SetNX method")
//			},
//		}
//
//		// use mockedStorage in code that requires Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// SetNXFunc mocks the SetNX method.
	SetNXFunc func(ctx context.Context, e []broker.Event) ([]bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// SetNX holds details about calls to the SetNX method.
		SetNX []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// E is the e argument value.
			E []broker.Event
		}
	}
	lockSetNX sync.RWMutex
}

// SetNX calls SetNXFunc.
func (mock *StorageMock) SetNX(ctx context.Context, e []broker.Event) ([]bool, error) {
	if mock.SetNXFunc == nil {
		panic("StorageMock.SetNXFunc: method is nil but Storage.SetNX was just called")
	}
	callInfo := struct {
		Ctx context.Context
		E   []broker.Event
	}{
		Ctx: ctx,
		E:   e,
	}
	mock.lockSetNX.Lock()
	mock.calls.SetNX = append(mock.calls.SetNX, callInfo)
	mock.lockSetNX.Unlock()
	return mock.SetNXFunc(ctx, e)
}

// SetNXCalls gets all the calls that were made to SetNX.
// Check the length with:
//
//	len(mockedStorage.SetNXCalls())
func (mock *StorageMock) SetNXCalls() []struct {
	Ctx context.Context
	E   []broker.Event
} {
	var calls []struct {
		Ctx context.Context
		E   []broker.Event
	}
	mock.lockSetNX.RLock()
	calls = mock.calls.SetNX
	mock.lockSetNX.RUnlock()
	return calls
}

// Ensure, that TxManagerMock does implement TxManager.
// If this is not the case, regenerate this file with moq.
var _ TxManager = &TxManagerMock{}

// TxManagerMock is a mock implementation of TxManager.
//
//	func TestSomethingThatUsesTxManager(t *testing.T) {
//
//		// make and configure a mocked TxManager
//		mockedTxManager := &TxManagerMock{
//			DoFunc: func(ctx context.Context, fn func(context.Context) error) error {
//				panic("mock out the Do method")
//			},
//		}
//
//		// use mockedTxManager in code that requires TxManager
//		// and then make assertions.
//
//	}
type TxManagerMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, fn func(context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(context.Context) error
		}
	}
	lockDo sync.RWMutex
}

// Do calls DoFunc.
func (mock *TxManagerMock) Do(ctx context.Context, fn func(context.Context) error) error {
	if mock.DoFunc == nil {
		panic("TxManagerMock.DoFunc: method is nil but TxManager.Do was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, fn)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedTxManager.DoCalls())
func (mock *TxManagerMock) DoCalls() []struct {
	Ctx context.Context
	Fn  func(context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(context.Context) error
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}
